### ISSUE TITLE
ca.srl

### ISSUE THREAD

**Issue by cart88** [yiguihai/openwrt-UnblockNeteaseMusic#1]
ENVIORMENT：
openwrt 19.07.08 not lede
comile enviroment: debian 9
LOG：
/home/lpz/19.07/openwrt/staging_dir/host/bin/upx --best --ultra-brute /home/lpz/ 19.07/openwrt/build_dir/target-mipsel_24kc_musl/UnblockNeteaseMusic/.go_work/bui ld/bin/linux_mipsle/UnblockNeteaseMusic                                                                 Ultimate Packer for eXecutables                                                     Copyright (C) 1996 - 2021                              UPX 4.0.0       Markus Oberhumer, Laszlo Molnar & John Reiser    Jan 1st 2021                                                                                             File size         Ratio      Format      Name                               --------------------   ------   -----------   -----------                        6238080 ->   1730716   27.74%  linux/mipsel   UnblockNeteaseMusic                                                                                              Packed 1 file.                                                                   chmod +wx /home/lpz/19.07/openwrt/build_dir/target-mipsel_24kc_musl/UnblockNetea seMusic/.go_work/build/bin/linux_mipsle/UnblockNeteaseMusic                      touch /home/lpz/19.07/openwrt/build_dir/target-mipsel_24kc_musl/UnblockNeteaseMu sic/.built                                                                       rm -rf /home/lpz/19.07/openwrt/build_dir/target-mipsel_24kc_musl/UnblockNeteaseM usic/.pkgdir/UnblockNeteaseMusic.installed /home/lpz/19.07/openwrt/build_dir/tar get-mipsel_24kc_musl/UnblockNeteaseMusic/.pkgdir/UnblockNeteaseMusic             mkdir -p /home/lpz/19.07/openwrt/build_dir/target-mipsel_24kc_musl/UnblockNeteas eMusic/.pkgdir/UnblockNeteaseMusic                                               install -d -m0755 /home/lpz/19.07/openwrt/build_dir/target-mipsel_24kc_musl/Unbl ockNeteaseMusic/.pkgdir/UnblockNeteaseMusic/usr/bin                              install -m0755 /home/lpz/19.07/openwrt/build_dir/target-mipsel_24kc_musl/Unblock NeteaseMusic/.go_work/build/bin/linux_mipsle/UnblockNeteaseMusic /home/lpz/19.07 /openwrt/build_dir/target-mipsel_24kc_musl/UnblockNeteaseMusic/.pkgdir/UnblockNe teaseMusic/usr/bin/UnblockNeteaseMusic                                           install -d -m0755 /home/lpz/19.07/openwrt/build_dir/target-mipsel_24kc_musl/Unbl ockNeteaseMusic/.pkgdir/UnblockNeteaseMusic/etc/init.d                           install -m0755 unblockneteasemusic.init /home/lpz/19.07/openwrt/build_dir/target -mipsel_24kc_musl/UnblockNeteaseMusic/.pkgdir/UnblockNeteaseMusic/etc/init.d/unb lockneteasemusic                                                                 install -d -m0755 /home/lpz/19.07/openwrt/build_dir/target-mipsel_24kc_musl/Unbl ockNeteaseMusic/.pkgdir/UnblockNeteaseMusic/usr/share/UnblockNeteaseMusic        install -m0600 ca.crt /home/lpz/19.07/openwrt/build_dir/target-mipsel_24kc_musl/ UnblockNeteaseMusic/.pkgdir/UnblockNeteaseMusic/usr/share/UnblockNeteaseMusic/ca .crt                                                                             install -m0600 ca.key /home/lpz/19.07/openwrt/build_dir/target-mipsel_24kc_musl/ UnblockNeteaseMusic/.pkgdir/UnblockNeteaseMusic/usr/share/UnblockNeteaseMusic/ca .key                                                                             install -m0600 ca.srl  /home/lpz/19.07/openwrt/build_dir/target-mipsel_24kc_musl /UnblockNeteaseMusic/.pkgdir/UnblockNeteaseMusic/usr/share/UnblockNeteaseMusic/c a.srl                                                                            install: cannot stat 'ca.srl': No such file or directory                         Makefile:109: recipe for target '/home/lpz/19.07/openwrt/build_dir/target-mipsel _24kc_musl/UnblockNeteaseMusic/.pkgdir/UnblockNeteaseMusic.installed' failed     make[2]: *** [/home/lpz/19.07/openwrt/build_dir/target-mipsel_24kc_musl/UnblockN eteaseMusic/.pkgdir/UnblockNeteaseMusic.installed] Error 1                       make[2]: Leaving directory '/home/lpz/19.07/openwrt/package/UnblockNeteaseMusic' time: package/UnblockNeteaseMusic/compile#948.90#24.04#868.29                    package/Makefile:111: recipe for target 'package/UnblockNeteaseMusic/compile' fa iled                                                                             make[1]: *** [package/UnblockNeteaseMusic/compile] Error 2                       make[1]: Leaving directory '/home/lpz/19.07/openwrt'                             /home/lpz/19.07/openwrt/include/toplevel.mk:225: recipe for target 'package/Unbl ockNeteaseMusic/compile' failed                                                  make: *** [package/UnblockNeteaseMusic/compile] Error 2
--

**Comment by cart88** [comment]
in Makefile
i suppose here is the problem,may i comment it ?

$(INSTALL_CONF) ca.srl  $(1)/usr/share/UnblockNeteaseMusic/ca.srl

**Comment by yiguihai** [comment]
> in Makefile
> i suppose here is the problem,may i comment it ?
> 
> $(INSTALL_CONF) ca.srl $(1)/usr/share/UnblockNeteaseMusic/ca.srl

#生成证书
bash package/UnblockNeteaseMusic/createCertificate.sh

**Comment by yiguihai** [comment]
编译前麻烦认证阅读一下 README.md 的说明！还有把出错信息以代码方式显示不然显得来势汹汹兴师问罪毕竟我不欠谁的。
